from .vocabulary import convolution_layer_vocabulary, activation_functions_vocabulary, pooling_layer_vocabulary, head_vocabulary_C, head_vocabulary_D, head_vocabulary_S
from .vocabulary import layer_parameters, parameter_vocabulary 
